/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kokkbdyqrfmkdwfmvfub"
export const publishableKey = "sb_publishable_VONJjWni89fsE4vjDHCGug_vemosURF"
export const publicAnonKey = publishableKey